export const outlayList = [
  { name: 'icon-gouwu', tagName: '购物', id: 3 },
  { name: 'icon-jiaotong', tagName: '交通', id: 1 },
  { name: 'icon-duoren', tagName: '人情', id: 9 },
  { name: 'icon-yiliao', tagName: '医疗', id: 7 },
  { name: 'icon-canyin', tagName: '餐饮', id: 5 },
  { name: 'icon-fushi1', tagName: '服饰', id: 4 },
  { name: 'icon-lvhang', tagName: '旅行', id: 8 },
  { name: 'icon-riyong', tagName: '日用', id: 2 },
  { name: 'icon-xuexi1', tagName: '学习', id: 6 },
  { name: 'icon-tongxun', tagName: '通讯', id: 17 },
  { name: 'icon-meirong', tagName: '美容', id: 18 },
  { name: 'icon-chongwu', tagName: '宠物', id: 19 },
  { name: 'icon-shuma', tagName: '数码', id: 20 },
  { name: 'icon-bangong', tagName: '办公', id: 21 },
  { name: 'icon-cheqiche', tagName: '汽车', id: 22 },
  { name: 'icon-yanjiu', tagName: '烟酒', id: 23 },
  { name: 'icon-weixiu', tagName: '维修', id: 24 },
  { name: 'icon-haizi', tagName: ' 孩子', id: 25 },
  { name: 'icon-qita', tagName: '其他', id: 10 },
];
export const incomeList = [
  { name: 'icon-gongzi', tagName: '工资', id: 11 },
  { name: 'icon-jiangjin', tagName: '奖金', id: 12 },
  { name: 'icon-zhuanzhang', tagName: '转账', id: 13 },
  { name: 'icon-tuikuan', tagName: '退款', id: 15 },
  { name: 'icon-licai', tagName: '理财', id: 14 },
  { name: 'icon-qita', tagName: '其他', id: 16 },
];
